cask_args appdir: '/Applications'

tap "derailed/k9s"

brew "awscli"
brew "fzf"
brew "golang"
brew "golangci-lint"
brew "htop"
brew "httpie"
brew "jq"
brew "kind"
brew "kubectx"
brew "neovim"
brew "tmux"
brew "tree"
brew "yq"
brew "jandedobbeleer/oh-my-posh/oh-my-posh"